"""Embed the bundled .scl temperaments into the web app as JavaScript data.

The .scl files are durable assets (DESIGN.md section 11) and the web port must
use exactly the same bytes, not a transcription. This tool writes
docs/core/temperaments.js from data/temperaments/*.scl verbatim; the web side
parses the text with its own Scala parser, so the parser is exercised on real
data and the two implementations cannot drift apart on the numbers.

Run:  python -m flutetrainer.tools.make_web_temperaments
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "flutetrainer" / "data" / "temperaments"
TARGET = ROOT / "docs" / "core" / "temperaments.js"

# Display order and short help lines, both languages. Musical one-liners for a
# player choosing, not a treatise; the help page expands on them.
ENTRIES = (
    ("vallotti", {
        "en": "Well temperament: every key usable, thirds best in the home keys.",
        "fr": "Tempérament bien tempéré : toutes les tonalités jouables, tierces meilleures dans les tons voisins.",
    }),
    ("meantone_quarter", {
        "en": "Quarter-comma meantone: pure major thirds, a wolf fifth on G#–Eb.",
        "fr": "Mésotonique au quart de comma : tierces majeures pures, quinte du loup sur sol♯–mi♭.",
    }),
    ("werckmeister3", {
        "en": "Werckmeister III: circulating, C major purest, sharp keys harsher.",
        "fr": "Werckmeister III : circulant, do majeur le plus pur, tons diésés plus durs.",
    }),
    ("kirnberger3", {
        "en": "Kirnberger III: a pure C–E third, otherwise close to Vallotti.",
        "fr": "Kirnberger III : tierce do–mi pure, proche de Vallotti par ailleurs.",
    }),
    ("equal", {
        "en": "Equal temperament: the modern control; every third equally impure.",
        "fr": "Tempérament égal : la référence moderne ; toutes les tierces également fausses.",
    }),
)


def main() -> None:
    parts = [
        "/* GENERATED by flutetrainer/tools/make_web_temperaments.py -- do not edit.",
        " * The .scl texts below are byte-for-byte the bundled data files; the web",
        " * port parses them with its own Scala parser (core/tuning.js). */",
        "",
        "export const TEMPERAMENTS = Object.freeze({",
    ]
    for name, help_text in ENTRIES:
        text = (SOURCE / f"{name}.scl").read_text(encoding="utf-8")
        parts.append(f"  {name}: Object.freeze({{")
        parts.append(f"    scl: {json.dumps(text, ensure_ascii=False)},")
        parts.append(f"    help: {json.dumps(help_text, ensure_ascii=False)},")
        parts.append("  }),")
    parts.append("});")
    parts.append("")
    parts.append("export const TEMPERAMENT_ORDER = Object.freeze("
                 + json.dumps([name for name, _ in ENTRIES]) + ");")
    parts.append("")
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(ENTRIES)} temperaments)")


if __name__ == "__main__":
    main()
